<?php

if(function_exists("register_field_group"))
{

  // Homepage template
  register_field_group(array (
    'id' => 'acf_main-call-to-action',
    'title' => 'Main call to action',
    'fields' => array (
      array (
        'key' => 'field_543561833db70',
        'label' => 'Main button description',
        'name' => 'main_button_description',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5435618c3db71',
        'label' => 'Main button URL',
        'name' => 'main_button_url',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'page-home.php',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'acf_after_title',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
  
  register_field_group(array (
    'id' => 'acf_images',
    'title' => 'Images',
    'fields' => array (
      array (
        'key' => 'field_54356c76e3ff4',
        'label' => 'Image 1',
        'name' => 'image_1',
        'type' => 'image',
        'save_format' => 'object',
        'preview_size' => 'thumbnail',
        'library' => 'all',
      ),
      array (
        'key' => 'field_54356c9ae3ff5',
        'label' => 'Description 1',
        'name' => 'description_1',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_54356cabe3ff6',
        'label' => 'URL 1',
        'name' => 'url_1',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_54356cb1e3ff7',
        'label' => 'Image 2',
        'name' => 'image_2',
        'type' => 'image',
        'save_format' => 'object',
        'preview_size' => 'thumbnail',
        'library' => 'all',
      ),
      array (
        'key' => 'field_54356cbde3ff8',
        'label' => 'Description 2',
        'name' => 'description_2',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_54356cc4e3ff9',
        'label' => 'URL 2',
        'name' => 'url_2',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_54356cc9e3ffa',
        'label' => 'Image 3',
        'name' => 'image_3',
        'type' => 'image',
        'save_format' => 'object',
        'preview_size' => 'thumbnail',
        'library' => 'all',
      ),
      array (
        'key' => 'field_54356cd6e3ffb',
        'label' => 'Description 3',
        'name' => 'description_3',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_54356ce3e3ffc',
        'label' => 'URL 3',
        'name' => 'url_3',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'page-home.php',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));

  register_field_group(array (
    'id' => 'acf_link-to-the-news-page-2',
    'title' => 'Link to the News page',
    'fields' => array (
      array (
        'key' => 'field_543c037dba0bf',
        'label' => 'News page URL',
        'name' => 'news_page_url',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'page-home.php',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));

  register_field_group(array (
    'id' => 'acf_social-media',
    'title' => 'Social media',
    'fields' => array (
      array (
        'key' => 'field_54356d3939198',
        'label' => 'Profile 1',
        'name' => 'profile_1',
        'type' => 'select',
        'choices' => array (
          'facebook' => 'Facebook',
          'twitter' => 'Twitter',
          'linkedin' => 'LinkedIn',
          'googleplus' => 'Google+',
          'flickr' => 'Flickr',
          'youtube' => 'YouTube',
        ),
        'default_value' => '',
        'allow_null' => 1,
        'multiple' => 0,
      ),
      array (
        'key' => 'field_54356e0439199',
        'label' => 'Profile 1 URL',
        'name' => 'profile_1_url',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_54356e0f3919a',
        'label' => 'Profile 2',
        'name' => 'profile_2',
        'type' => 'select',
        'choices' => array (
          'facebook' => 'Facebook',
          'twitter' => 'Twitter',
          'linkedin' => 'LinkedIn',
          'googleplus' => 'Google+',
          'flickr' => 'Flickr',
          'youtube' => 'YouTube',
        ),
        'default_value' => '',
        'allow_null' => 1,
        'multiple' => 0,
      ),
      array (
        'key' => 'field_54356e1b3919b',
        'label' => 'Profile 2 URL',
        'name' => 'profile_2_url',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_54356e293919c',
        'label' => 'Profile 3',
        'name' => 'profile_3',
        'type' => 'select',
        'choices' => array (
          'facebook' => 'Facebook',
          'twitter' => 'Twitter',
          'linkedin' => 'LinkedIn',
          'googleplus' => 'Google+',
          'flickr' => 'Flickr',
          'youtube' => 'YouTube',
        ),
        'default_value' => '',
        'allow_null' => 1,
        'multiple' => 0,
      ),
      array (
        'key' => 'field_54356e333919d',
        'label' => 'Profile 3 URL',
        'name' => 'profile_3_url',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'page-home.php',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'side',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));

  register_field_group(array (
    'id' => 'acf_side-banner',
    'title' => 'Side banner',
    'fields' => array (
      array (
        'key' => 'field_543c05975b673',
        'label' => 'Banner title',
        'name' => 'banner_title',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_543c059e5b674',
        'label' => 'Banner description',
        'name' => 'banner_description',
        'type' => 'textarea',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'formatting' => 'br',
      ),
      array (
        'key' => 'field_543c05ab5b675',
        'label' => 'Banner URL',
        'name' => 'banner_url',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_543c05b35b676',
        'label' => 'Banner URL description',
        'name' => 'banner_url_description',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'page-home.php',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'side',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));

}
